export * from './task-templates/common.ts'
export * as Task from './task-templates/task-template.ts'
export * as Store from './task-templates/store.ts'
export * as single_action_task from './task-templates/single-action-task-template.ts'
export { SomeActionOneTimeTaskTemplate } from './task-templates/single-action-task-template.ts'