import { Id } from '/db/id.ts'
import { Now } from "/utility/time.ts"
import { Due } from '/db/due-templates.ts'
import { Null, msec } from "/utility/ulib.ts"
import { Crg, JsonRepr } from "./typings.ts"
import { SingleActionTask } from '/db/tasks/single-action-task.ts'
import { store as TASKS_STORE } from '/db/tasks/store.ts'

export class SingleActionTaskTemplate {
  /** Id of this template. */
  id: Id
  /** Due of tasks generated by this template. */
  due: Null<Due.DueTemplate> = null
  /** Description of this template and tasks generated by it. */
  description: string
  /** Creation date of this template. */
  creationDate: msec

  constructor(arg: Crg) {
    this.id = arg.id
    this.description = arg.description
    this.creationDate = arg.creationDate
  }

  new() {
    return SingleActionTask.new({
      id: Id(),
      due: this.due?.new() ?? null,
      isComplete: false,
      description: this.description,
      creationDate: Now(),
      completionDate: null,
    })
  }

  newAndAdd() {
    TASKS_STORE.addOne(this.new())
  }

  jsonify(): JsonRepr {
    return {
      id: this.id,
      due: this.due?.jsonify() ?? null,
      description: this.description,
      creationDate: this.creationDate,
    }
  }
}