import { Now } from "/utility/time.ts"
import { msec } from "/utility/ulib.ts"
import { Kind } from "../common.ts"
import { DueTemplate } from '/db/due-templates/due.ts'
import { Crg, JsonRepr } from './typings.ts'
import { DueAfterMilliseconds } from "/db/dues/after-milliseconds.ts"

export class DueAfterMillisecondsTemplate extends DueTemplate {
  /** Value of the `dueAfter` property of dues generated by this template. */
  dueAfter: msec

  constructor(arg: Crg) {
    super()
    this.dueAfter = arg.dueAfter
  }

  get kind(): Kind {
    return Kind.DueAfterMillisecondsTemplate
  }

  new() {
    return new DueAfterMilliseconds({
      from: Now(),
      dueAfter: this.dueAfter,
    })
  }
  
  jsonify(): JsonRepr {
    return {
      ...super.jsonify(),
      dueAfter: this.dueAfter,
    }
  }
}